
name: CI/CD Pipeline

# Triggers the workflow on push or pull request events
on:
  push:
    branches: ["main", "test"]
  pull_request:
    branches: ["main", "test"]

jobs:

  # ==============================
  # Continuous Integration
  # ==============================
  Build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Build Done
        run: echo "Build Done"



  # ==============================
  # Continuous Deployment
  # ==============================
  Deploy:
    name: Deploy to Production
    needs: Build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Build Done
        run: echo "Deployed"
