name: ci
 on:
 push:
 branches:
   - main
   - test
   - release/*
   - patch/*
 pull:
 branches:
   - main
   - test
   - release/*
   - patch/*
jobs:
	build:
	name: sanjay
	runs-on: ubuntu-latest
	steps:
      # 1. Fetch source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # 3. Build and run tests
      - name: Build and Test
        run: mvn clean verify

      # 4. Upload generated JAR
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar	
	
